Game.Tile.T = {
        WALL: new Game.Tile({ name: 'wall', char: '#', fg: '#FFFFFF', bg: "#000000", isPassable: false }),
        GROUND: new Game.Tile({ name: 'ground', char: '.', fg: '#FEFEFE', bg: "#000000", isPassable: true }),
        //PLAYER: new Game.Tile({ name: 'player', char: '@', fg: '#FF6666', bg: "#000000", isPassable: false }),
        VOID: new Game.Tile({ name: 'void', char: '#', fg: '#000000', bg: "#000000", isPassable: false }),
        TREE: new Game.Tile({ name: 'tree', char: '♣', fg: '#4C9900', bg: "#000000", isPassable: true }),
        SHRUB: new Game.Tile({ name: 'shrub', char: '„', fg: '#4C9900', bg: "#000000", isPassable: true }),
        FLOWER: new Game.Tile({ 
		name: 'flower',
		char: '', 
		fg: '#DADF42',
		bg: "#000000", 
		isPassable: true,
		sustainAmount: 30,
       		mixins: [Game.Mixins.CreatureEatable] }),
        DOOR_OPEN: new Game.Tile({ name: 'door_open', char: '-', fg: '#994C00', isPassable: true, door: true, isOpen: true }),
        DOOR_CLOSED: new Game.Tile({ name: 'door_closed', char: '+', fg: '#994C00', isPassable: false, door: true, isOpen: false }),
        HOUSE_FLOOR: new Game.Tile({ name: 'house_floor', char: '☷', fg: '#544433', isPassable: true }),
        HOUSE_H_WALL: new Game.Tile({ name: 'house_horizontal_wall', char: '═', fg: '#808080', isPassable: false }),
        HOUSE_V_WALL: new Game.Tile({ name: 'house_vertical_wall', char: '║', fg: '#808080', isPassable: false  }),
        HOUSE_ULC_WALL: new Game.Tile({ name: 'house_upper_left_corner_wall', char: '╔', fg: '#808080', isPassable: false  }),
        HOUSE_URC_WALL: new Game.Tile({ name: 'house_upper_right_corner_wall', char: '╗', fg: '#808080', isPassable: false  }),
        HOUSE_LLC_WALL: new Game.Tile({ name: 'house_lower_left_corner_wall', char: '╚', fg: '#808080', isPassable: false  }),
        HOUSE_LRC_WALL: new Game.Tile({ name: 'house_lower_right_corner_wall', char: '╝', fg: '#808080', isPassable: false  }), 
        WATER: new Game.Tile({ name: 'water', char: '▒', fg: '#0066CC', isPassable: true, isSwimmable: true, hydrateAmount: 50, mixins: [Game.Mixins.Potable]}),
};
